[package]
name = "reversi_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.8.0-beta.0"
ic-cdk-macros = "0.8.0-beta.0"
candid = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"